[tool.poetry]
name = "proj"
version = "0.1.0"
description = ""
authors = []
packages = []

[tool.poetry.dependencies]
python = "^3.10"
pathdep = { path = "pathdep" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
